//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerApplication.Common.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureEs_ES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureEs_ES() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulerApplication.Common.Cultures.CultureEs-ES", typeof(CultureEs_ES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre todos los días de {0} a {1}. El horario se utilizará el {2} a las {3} comenzando el {4}..
        /// </summary>
        internal static string DailyDescription_Range {
            get {
                return ResourceManager.GetString("DailyDescription_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre una vez a las {0}. El horario se utilizará el {1} a las {2} comenzando el {3}..
        /// </summary>
        internal static string DailyDescriptionSingle {
            get {
                return ResourceManager.GetString("DailyDescriptionSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intervalo inválido.
        /// </summary>
        internal static string ExecutionTimeGeneratorInvalidIntervalExc {
            get {
                return ResourceManager.GetString("ExecutionTimeGeneratorInvalidIntervalExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de configuración desconocido.
        /// </summary>
        internal static string ExecutionTimeGeneratorUnknownConfigurationExc {
            get {
                return ResourceManager.GetString("ExecutionTimeGeneratorUnknownConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primero.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cuarto.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viernes.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunes.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre el día {0} de cada {1} mes(es). El horario se utilizará el {2} a las {3} comenzando el {4}..
        /// </summary>
        internal static string MonthlyDescription_AnyDay {
            get {
                return ResourceManager.GetString("MonthlyDescription_AnyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre el {0} {1} de cada {2} mes(es). El horario se utilizará el {3} a las {4} comenzando el {5}..
        /// </summary>
        internal static string MonthlyDescription_DayOption {
            get {
                return ResourceManager.GetString("MonthlyDescription_DayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre el día {0} de cada {1} mes(es). El horario se utilizará el {2} a las {3} comenzando el {4}..
        /// </summary>
        internal static string MonthlyDescription_SpecificDay {
            get {
                return ResourceManager.GetString("MonthlyDescription_SpecificDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de configuración inválida para MonthlyDateCalculator..
        /// </summary>
        internal static string MonthlySchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("MonthlySchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre una vez. El horario se utilizará el {0} a las {1} comenzando el {2}..
        /// </summary>
        internal static string OnceDescription {
            get {
                return ResourceManager.GetString("OnceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de configuración inválida para OnceDateCalculator..
        /// </summary>
        internal static string OnceSchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("OnceSchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha de configuración no puede estar en el pasado..
        /// </summary>
        internal static string OnceSchedulerConfigurationPastConfigurationExc {
            get {
                return ResourceManager.GetString("OnceSchedulerConfigurationPastConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sábado.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de configuración no soportada..
        /// </summary>
        internal static string ScheduleTypeFactoryUnsupportedConfigurationExc {
            get {
                return ResourceManager.GetString("ScheduleTypeFactoryUnsupportedConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segundo.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de configuración inválida para SpecificDayStrategy..
        /// </summary>
        internal static string SpecificDayStrategySchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("SpecificDayStrategySchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domingo.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tercer.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jueves.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Martes.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Miércoles.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Día de la semana.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fin de semana.
        /// </summary>
        internal static string WeekendDay {
            get {
                return ResourceManager.GetString("WeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocurre cada {0} semana(s) los {1}. El horario se utilizará el {2} a las {3} comenzando el {4}..
        /// </summary>
        internal static string WeeklyDescription {
            get {
                return ResourceManager.GetString("WeeklyDescription", resourceCulture);
            }
        }
    }
}
