//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchedulerApplication.Common.Cultures {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CultureEn_GB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CultureEn_GB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SchedulerApplication.Common.Cultures.CultureEn-GB", typeof(CultureEn_GB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every day from {0} to {1}. Schedule will be used on {2} at {3} starting on {4}..
        /// </summary>
        internal static string DailyDescription_Range {
            get {
                return ResourceManager.GetString("DailyDescription_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once at {0}. Schedule will be used on {1} at {2} starting on {3}..
        /// </summary>
        internal static string DailyDescriptionSingle {
            get {
                return ResourceManager.GetString("DailyDescriptionSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid interval.
        /// </summary>
        internal static string ExecutionTimeGeneratorInvalidIntervalExc {
            get {
                return ResourceManager.GetString("ExecutionTimeGeneratorInvalidIntervalExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown configuration type.
        /// </summary>
        internal static string ExecutionTimeGeneratorUnknownConfigurationExc {
            get {
                return ResourceManager.GetString("ExecutionTimeGeneratorUnknownConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to first.
        /// </summary>
        internal static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fourth.
        /// </summary>
        internal static string Fourth {
            get {
                return ResourceManager.GetString("Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs on day {0} of every {1} month(s). Schedule will be used on {2} at {3} starting on {4}..
        /// </summary>
        internal static string MonthlyDescription_AnyDay {
            get {
                return ResourceManager.GetString("MonthlyDescription_AnyDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs on the {0} {1} of every {2} month(s). Schedule will be used on {3} at {4} starting on {5}..
        /// </summary>
        internal static string MonthlyDescription_DayOption {
            get {
                return ResourceManager.GetString("MonthlyDescription_DayOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs on day {0} of every {1} month(s). Schedule will be used on {2} at {3} starting on {4}..
        /// </summary>
        internal static string MonthlyDescription_SpecificDay {
            get {
                return ResourceManager.GetString("MonthlyDescription_SpecificDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration type for MonthlyDateCalculator..
        /// </summary>
        internal static string MonthlySchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("MonthlySchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs once. Schedule will be used on {0} at {1} starting on {2}..
        /// </summary>
        internal static string OnceDescription {
            get {
                return ResourceManager.GetString("OnceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration type for OnceDateCalculator..
        /// </summary>
        internal static string OnceSchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("OnceSchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration date time cannot be in the past..
        /// </summary>
        internal static string OnceSchedulerConfigurationPastConfigurationExc {
            get {
                return ResourceManager.GetString("OnceSchedulerConfigurationPastConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported configuration type..
        /// </summary>
        internal static string ScheduleTypeFactoryUnsupportedConfigurationExc {
            get {
                return ResourceManager.GetString("ScheduleTypeFactoryUnsupportedConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to second.
        /// </summary>
        internal static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration type for SpecificDayStrategy..
        /// </summary>
        internal static string SpecificDayStrategySchedulerConfigurationInvalidConfigurationExc {
            get {
                return ResourceManager.GetString("SpecificDayStrategySchedulerConfigurationInvalidConfigurationExc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to third.
        /// </summary>
        internal static string Third {
            get {
                return ResourceManager.GetString("Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekday.
        /// </summary>
        internal static string Weekday {
            get {
                return ResourceManager.GetString("Weekday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekend day.
        /// </summary>
        internal static string WeekendDay {
            get {
                return ResourceManager.GetString("WeekendDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs every {0} week(s) on {1}. Schedule will be used on {2} at {3} starting on {4}..
        /// </summary>
        internal static string WeeklyDescription {
            get {
                return ResourceManager.GetString("WeeklyDescription", resourceCulture);
            }
        }
    }
}
